# Exported from Render on 2026-04-30T12:29:01Z
version: "1"
projects:
- name: Planting-Optimisation-Tool
  environments:
  - name: Production
    services:
    - type: web
      name: pot-backend
      runtime: docker
      repo: https://github.com/Chameleon-company/Planting-Optimisation-Tool
      plan: starter
      preDeployCommand: cd /app/backend && .venv/bin/alembic upgrade head
      envVars:
      - key: GEE_SERVICE_ACCOUNT
        sync: false
      - key: GEE_KEY_JSON
        sync: false
      - key: RATELIMIT_ENABLED
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PORT
        sync: false
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: pot-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: pot-db
          property: host
      - key: POSTGRES_DB
        sync: false
      - key: REDIS_URL
        fromService:
          name: pot-redis
          type: keyvalue
          property: connectionString
      - key: TESTING
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
      region: singapore
      dockerContext: .
      dockerfilePath: ./backend/Dockerfile
      autoDeployTrigger: commit
    - type: web
      name: pot-frontend
      runtime: static
      repo: https://github.com/Chameleon-company/Planting-Optimisation-Tool
      envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_SPACE_ID
        sync: false
      - key: VITE_ACCESS_TOKEN
        sync: false
      buildCommand: npm install; npm run build
      staticPublishPath: build/dist
      domains:
      - www.planting-optimisation-tool.app
      - planting-optimisation-tool.app
      routes:
      - type: rewrite
        source: /*
        destination: /index.html
      autoDeployTrigger: commit
      rootDir: frontend
    - type: keyvalue
      name: pot-redis
      plan: free
      region: singapore
      maxmemoryPolicy: allkeys-lru
      ipAllowList: []
    databases:
    - name: pot-db
      databaseName: pot_db_zjyl
      user: pot_db_zjyl_user
      plan: free
      region: singapore
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "15"
