"""Initial schema

Revision ID: 08144ce28c39
Revises: 
Create Date: 2025-12-11 18:05:44.521910

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '08144ce28c39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agroforestry_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('soil_textures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texture_name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('texture_name')
    )
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rainfall_mm', sa.Integer(), nullable=False),
    sa.Column('temperature_celsius', sa.Integer(), nullable=False),
    sa.Column('elevation_m', sa.Integer(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('soil_texture_id', sa.Integer(), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('coastal', sa.Boolean(), nullable=False),
    sa.Column('riparian', sa.Boolean(), nullable=False),
    sa.Column('nitrogen_fixing', sa.Boolean(), nullable=False),
    sa.Column('shade_tolerant', sa.Boolean(), nullable=False),
    sa.Column('bank_stabilising', sa.Boolean(), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['soil_texture_id'], ['soil_textures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('rainfall_mm_min', sa.Integer(), nullable=False),
    sa.Column('rainfall_mm_max', sa.Integer(), nullable=False),
    sa.Column('temperature_celsius_min', sa.Integer(), nullable=False),
    sa.Column('temperature_celsius_max', sa.Integer(), nullable=False),
    sa.Column('elevation_m_min', sa.Integer(), nullable=False),
    sa.Column('elevation_m_max', sa.Integer(), nullable=False),
    sa.Column('ph_min', sa.Float(), nullable=False),
    sa.Column('ph_max', sa.Float(), nullable=False),
    sa.Column('preferred_soil_texture_id', sa.Integer(), nullable=False),
    sa.Column('coastal', sa.Boolean(), nullable=False),
    sa.Column('riparian', sa.Boolean(), nullable=False),
    sa.Column('nitrogen_fixing', sa.Boolean(), nullable=False),
    sa.Column('shade_tolerant', sa.Boolean(), nullable=False),
    sa.Column('bank_stabilising', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['preferred_soil_texture_id'], ['soil_textures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_agroforestry_association',
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('agroforestry_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agroforestry_type_id'], ['agroforestry_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('farm_id', 'agroforestry_type_id')
    )
    op.create_table('species_agroforestry_association',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('agroforestry_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agroforestry_type_id'], ['agroforestry_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('species_id', 'agroforestry_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_agroforestry_association')
    op.drop_table('farm_agroforestry_association')
    op.drop_table('species')
    op.drop_table('farms')
    op.drop_table('soil_textures')
    op.drop_table('agroforestry_types')
    # ### end Alembic commands ###
