"""Changed ph_max from 7.0 -> 6.5

Revision ID: a21b8babef99
Revises: 160313f63d58
Create Date: 2025-12-22 20:47:42.785471

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a21b8babef99'
down_revision: Union[str, Sequence[str], None] = '160313f63d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
