"""default farm attributes (coastal, riparian etc..)

Revision ID: 38c9de0fe996
Revises: 8ce19d41a4f1
Create Date: 2025-12-19 19:02:54.339397

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa
import geoalchemy2 # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '38c9de0fe996'
down_revision: Union[str, Sequence[str], None] = '8ce19d41a4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.add_column('farms', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'farms', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('soil_textures', sa.Column('name', sa.String(length=15), nullable=False))
    op.drop_constraint(op.f('soil_textures_texture_name_key'), 'soil_textures', type_='unique')
    op.create_unique_constraint(None, 'soil_textures', ['name'])
    op.drop_column('soil_textures', 'texture_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soil_textures', sa.Column('texture_name', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('soil_textures_name_key'), 'soil_textures', type_='unique')
    op.create_unique_constraint(op.f('soil_textures_texture_name_key'), 'soil_textures', ['texture_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('soil_textures', 'name')
    op.drop_constraint('fk_farms_user_id', 'farms', type_='foreignkey')
    op.drop_column('farms', 'user_id')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
