"""add species_dependency table

Revision ID: 2c230e5a4440
Revises: 2a53af31ea2e
Create Date: 2026-04-03 16:46:21.558126

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c230e5a4440'
down_revision: Union[str, Sequence[str], None] = '2a53af31ea2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focal_species_id', sa.Integer(), nullable=False),
    sa.Column('required_partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['focal_species_id'], ['species.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_partner_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_dependencies')
    # ### end Alembic commands ###
