""" add global weights tables

Revision ID: aee157e85e9c
Revises: f4746a1d68d7
Create Date: 2026-05-01 16:03:55.096632

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aee157e85e9c'
down_revision: Union[str, Sequence[str], None] = 'f4746a1d68d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_weights_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dataset_hash', sa.String(), nullable=False),
    sa.Column('bootstraps', sa.Integer(), nullable=False),
    sa.Column('bootstrap_early_stopped', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('mean_weight', sa.Float(), nullable=False),
    sa.Column('ci_lower', sa.Float(), nullable=False),
    sa.Column('ci_upper', sa.Float(), nullable=False),
    sa.Column('ci_width', sa.Float(), nullable=False),
    sa.Column('touches_zero', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['global_weights_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_weights')
    op.drop_table('global_weights_runs')
    # ### end Alembic commands ###
