"""Convert species-soil_texture from 1:M to M:M

Revision ID: 465f8691a2ae
Revises: 08144ce28c39
Create Date: 2025-12-11 18:32:00.422178

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '465f8691a2ae'
down_revision: Union[str, Sequence[str], None] = '08144ce28c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_soil_texture_association',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('soil_texture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['soil_texture_id'], ['soil_textures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'soil_texture_id')
    )
    op.drop_constraint(op.f('species_preferred_soil_texture_id_fkey'), 'species', type_='foreignkey')
    op.drop_column('species', 'preferred_soil_texture_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('preferred_soil_texture_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('species_preferred_soil_texture_id_fkey'), 'species', 'soil_textures', ['preferred_soil_texture_id'], ['id'], ondelete='CASCADE')
    op.drop_table('species_soil_texture_association')
    # ### end Alembic commands ###
